/**
 * modules/elara/elara-sessions.service.ts
 *
 * Two responsibilities:
 *
 * 1. saveElaraSession() — called at conversation end (paid tiers only).
 *    Writes grammar/fluency/vocab averages to elara_sessions so the
 *    dashboard "English Journey" chart has data to display.
 *
 * 2. Vocabulary reinforcement loop:
 *    - trackVocabErrors()     — called after every Elara message.
 *      Increments occurrence counts; auto-saves words that cross the
 *      3-strike threshold (same mistake in ≥3 sessions).
 *    - saveWordManually()     — user tapped a word in the UI.
 *    - getVocabList()         — returns the user's saved vocab list.
 *    - buildVocabSystemPrompt() — produces the injection block for future
 *      Elara system prompts (top 10 weak words).
 *
 * None of these functions throw — callers don't need try/catch.
 * Failures are logged but never crash the conversation.
 */

import { db }     from '../../core/database/client';
import { logger } from '../../infra/logger';

const log = logger.child({ module: 'elara-sessions' });

// ── Constants ─────────────────────────────────────────────────────────────

/** Auto-save a word after this many cross-session occurrences. */
const AUTO_SAVE_THRESHOLD = 3;

// ── Session-level vocab dedup (Bug 5 fix) ─────────────────────────────────
//
// The spec says "same mistake in ≥3 *sessions*" but the original code
// incremented the global counter on every message, so a word could hit the
// threshold within a single session.
//
// Fix: track which (userId, sessionId, wrongForm) tuples have already been
// counted in the current process lifetime. The first occurrence of a wrong
// form in a given session is debited to the global counter; subsequent
// occurrences in the same session are ignored. This is an in-memory set —
// it resets on process restart, which is fine: a crash/restart is a natural
// session boundary, and the set is bounded by the number of unique
// (user, session, word) triples that pass through this process.
//
// Map key: `${userId}:${sessionId}:${wrongForm}`
const _sessionVocabSeen = new Set<string>();

/**
 * Marks that `wrongForm` has been seen for `userId` in `sessionId`.
 * Returns true if this is the FIRST time we've seen it this session
 * (so the caller should increment the global counter), false if already seen.
 */
function _dedupVocabError(userId: string, sessionId: string, wrongForm: string): boolean {
  const key = `${userId}:${sessionId}:${wrongForm}`;
  if (_sessionVocabSeen.has(key)) return false;
  _sessionVocabSeen.add(key);
  return true;
}

// Prevent unbounded growth: prune entries for a session when it ends.
// Called by handleSaveSession (conversation end) via clearSessionVocabDedup.
export function clearSessionVocabDedup(userId: string, sessionId: string): void {
  // Iterate safely: collect keys first, then delete.
  const prefix = `${userId}:${sessionId}:`;
  for (const key of _sessionVocabSeen) {
    if (key.startsWith(prefix)) _sessionVocabSeen.delete(key);
  }
}

// ── Types ─────────────────────────────────────────────────────────────────

export interface ElaraScores {
  grammar_score: number | null;
  fluency_score: number | null;
  vocab_score:   number | null;
}

export interface VocabError {
  wrong:   string;
  correct: string;
  rule?:   string;
}

// ── 1. Session persistence ─────────────────────────────────────────────────

/**
 * Persists the rolling score averages from a completed Elara conversation.
 * Called at session end from the /english page (client POSTs to
 * POST /api/elara/sessions). Idempotent via client_session_id.
 *
 * @param userId            — authenticated user id
 * @param clientSessionId   — UUID generated by the client at conversation start
 * @param scores            — averaged grammar/fluency/vocab across all messages
 * @param messageCount      — number of user messages in the conversation
 * @param mode              — elara mode (conversation | topics | correction | vocabulary)
 */
export async function saveElaraSession(
  userId:          string,
  clientSessionId: string,
  scores:          ElaraScores,
  messageCount:    number,
  mode:            string,
): Promise<void> {
  try {
    await db.saveElaraSession({
      user_id:           userId,
      client_session_id: clientSessionId,
      grammar_score:     scores.grammar_score,
      fluency_score:     scores.fluency_score,
      vocab_score:       scores.vocab_score,
      message_count:     messageCount,
      mode,
    });
    log.info('Elara session saved', { userId, clientSessionId, scores, messageCount });
  } catch (err) {
    // Non-fatal — a failed write must never crash the UI flow.
    log.error('saveElaraSession failed (non-fatal)', { userId, clientSessionId, error: (err as Error).message });
  }
}

/**
 * Returns the last N elara sessions for a user, oldest-first for charting.
 */
export async function getElaraSessions(userId: string, limit = 30) {
  try {
    const rows = await db.getElaraSessions(userId, limit);
    return rows.reverse(); // DB returns newest-first; chart wants oldest-first
  } catch (err) {
    log.error('getElaraSessions failed', { userId, error: (err as Error).message });
    return [];
  }
}

// ── 2. Vocabulary tracker ──────────────────────────────────────────────────

/**
 * Processes a batch of errors flagged by Elara in a single message.
 * For each error:
 *   - If the word already exists → increment occurrence count.
 *   - If new → insert with occurrences = 1.
 *   - After increment, if occurrences ≥ AUTO_SAVE_THRESHOLD → mark auto_saved.
 *
 * Fire-and-forget: all DB ops are non-fatal.
 */
export async function trackVocabErrors(
  userId:    string,
  errors:    VocabError[],
  sessionId: string,    // client_session_id from the request body
): Promise<void> {
  if (!errors.length) return;

  await Promise.allSettled(
    errors.map(async (e) => {
      try {
        // Normalise to lowercase for deduplication
        const wrongForm = e.wrong.toLowerCase().trim();
        if (!wrongForm) return;

        // Bug 5 fix: only count the first occurrence per session.
        // If this (userId, sessionId, wrongForm) triple has already been
        // processed in this session, skip the global counter increment so
        // the 3-strike threshold truly means "3 sessions", not "3 messages".
        const isFirstInSession = _dedupVocabError(userId, sessionId, wrongForm);

        // Check if the word already exists
        const existing = await db.getVocabWordByWrongForm(userId, wrongForm);

        if (existing) {
          if (!isFirstInSession) return;  // already counted this session

          // Increment occurrence using PATCH (PostgREST arithmetic)
          const newOccurrences = (existing.occurrences ?? 1) + 1;
          await db.patchVocabOccurrences(userId, wrongForm, newOccurrences);

          // Auto-save threshold check
          if (newOccurrences >= AUTO_SAVE_THRESHOLD && !existing.auto_saved) {
            await db.markVocabAutoSaved(userId, wrongForm);
            log.info('Vocab word auto-saved (3-strike)', { userId, wrongForm, newOccurrences });
          }
        } else {
          // New word — insert with occurrences = 1.
          // isFirstInSession is always true for a brand-new word (it cannot
          // have been seen earlier in this session if it doesn't exist yet).
          await db.upsertVocabWord({
            user_id:        userId,
            wrong_form:     wrongForm,
            correct_form:   e.correct,
            rule:           e.rule ?? null,
            auto_saved:     false,
            manually_saved: false,
          });
        }
      } catch (err) {
        log.warn('trackVocabErrors — single word failed (non-fatal)', {
          userId, wrong: e.wrong, error: (err as Error).message,
        });
      }
    })
  );
}

/**
 * Marks a word as manually saved by the user tapping it in the UI.
 * Upserts first (in case the word was never auto-tracked yet) then sets
 * manually_saved = true.
 */
export async function saveWordManually(
  userId:      string,
  wrongForm:   string,
  correctForm: string,
  rule?:       string,
): Promise<void> {
  const normalised = wrongForm.toLowerCase().trim();
  if (!normalised) return;

  try {
    // Upsert so the word always exists before we patch
    await db.upsertVocabWord({
      user_id:        userId,
      wrong_form:     normalised,
      correct_form:   correctForm,
      rule:           rule ?? null,
      manually_saved: true,
    });
    await db.markVocabManuallySaved(userId, normalised);
    log.info('Vocab word manually saved', { userId, wrongForm: normalised });
  } catch (err) {
    log.error('saveWordManually failed (non-fatal)', { userId, wrongForm: normalised, error: (err as Error).message });
  }
}

/**
 * Returns the user's full saved vocab list (auto + manual) for the dashboard
 * and the /english vocab sidebar.
 */
export async function getVocabList(userId: string) {
  try {
    return await db.getVocabWords(userId);
  } catch (err) {
    log.error('getVocabList failed', { userId, error: (err as Error).message });
    return [];
  }
}

/**
 * Builds the vocabulary reinforcement block injected into the Elara system
 * prompt for future conversations.
 *
 * Returns an empty string when the user has no saved words yet (first session
 * or no repeating mistakes yet), so callers can simply append it without
 * branching.
 *
 * Example output:
 *
 *   VOCABULARY REINFORCEMENT:
 *   The user repeatedly makes these mistakes. Work them naturally into the
 *   conversation and correct the user if they use them wrong:
 *   1. "I am agree" → "I agree" (use "agree" not "am agree")
 *   2. "He go to school" → "He goes to school" (subject-verb agreement)
 *   ...
 *
 * Side effect: stamps last_reinforced_at on the words included so they
 * rotate out after a while (fire-and-forget, non-fatal).
 */
export async function buildVocabSystemPrompt(userId: string): Promise<string> {
  try {
    const words = await db.getTopWeakVocabWords(userId, 10);
    if (!words.length) return '';

    const lines = words.map((w, i) => {
      const ruleHint = w.rule ? ` (${w.rule})` : '';
      return `${i + 1}. "${w.wrong_form}" → "${w.correct_form}"${ruleHint}`;
    });

    // Fire-and-forget: stamp reinforced — failure must not block the conversation
    db.stampVocabReinforced(userId, words.map(w => w.wrong_form))
      .catch(err => log.warn('stampVocabReinforced failed (non-fatal)', { userId, error: String(err) }));

    return [
      '\n\nVOCABULARY REINFORCEMENT:',
      'The user has repeated these mistakes in past sessions. Work the correct forms naturally',
      'into conversation and gently correct the user if they make these errors again:',
      ...lines,
    ].join('\n');
  } catch (err) {
    log.error('buildVocabSystemPrompt failed (non-fatal)', { userId, error: (err as Error).message });
    return '';
  }
}
